// Package state handles terraform state operations (copy, backup, restore).
package state

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/chadac/tfsync/internal/terraform"
)

// Copier handles copying state between terraform configurations.
type Copier struct {
	binary string
}

// NewCopier creates a new state copier.
func NewCopier(binary string) *Copier {
	if binary == "" {
		binary = "tofu"
	}
	return &Copier{binary: binary}
}

// CopyResult contains the result of a state copy operation.
type CopyResult struct {
	// SourceResources is the list of resources in the source state
	SourceResources []string
	// LocalStatePath is the path to the local state file created
	LocalStatePath string
}

// CopyToLocal copies state from a source terraform config to a local state file.
// This pulls from the source's configured backend and writes to a local file.
func (c *Copier) CopyToLocal(ctx context.Context, sourceDir, targetDir string, backendConfig map[string]string) (*CopyResult, error) {
	// Initialize source to connect to its backend
	sourceCLI := terraform.NewCLI(c.binary, sourceDir)
	if len(backendConfig) > 0 {
		if err := sourceCLI.InitWithBackendConfig(ctx, backendConfig); err != nil {
			return nil, fmt.Errorf("failed to init source: %w", err)
		}
	} else {
		if err := sourceCLI.Init(ctx); err != nil {
			return nil, fmt.Errorf("failed to init source: %w", err)
		}
	}

	// Pull state from source
	stateData, err := sourceCLI.StatePull(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to pull source state: %w", err)
	}

	// Get source resources for reporting
	sourceResources, err := sourceCLI.StateList(ctx)
	if err != nil {
		// Non-fatal, just won't have resource list
		sourceResources = nil
	}

	// Write state to local file in target directory
	localStatePath := filepath.Join(targetDir, "terraform.tfstate")
	if err := os.WriteFile(localStatePath, stateData, 0644); err != nil {
		return nil, fmt.Errorf("failed to write local state: %w", err)
	}

	return &CopyResult{
		SourceResources: sourceResources,
		LocalStatePath:  localStatePath,
	}, nil
}

// InitTargetWithLocalBackend initializes the target directory with a local backend.
// This creates an override file to force local state.
func (c *Copier) InitTargetWithLocalBackend(ctx context.Context, targetDir string) error {
	// Create backend override to use local state
	overridePath := filepath.Join(targetDir, "backend_override.tf")
	overrideContent := `# Auto-generated by tfsync - DO NOT COMMIT
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
}
`
	if err := os.WriteFile(overridePath, []byte(overrideContent), 0644); err != nil {
		return fmt.Errorf("failed to write backend override: %w", err)
	}

	// Initialize target with local backend
	targetCLI := terraform.NewCLI(c.binary, targetDir)
	if err := targetCLI.Init(ctx); err != nil {
		return fmt.Errorf("failed to init target: %w", err)
	}

	return nil
}

// Cleanup removes generated files from the target directory.
func (c *Copier) Cleanup(targetDir string) error {
	files := []string{
		filepath.Join(targetDir, "backend_override.tf"),
		filepath.Join(targetDir, "terraform.tfstate"),
		filepath.Join(targetDir, "terraform.tfstate.backup"),
	}

	for _, f := range files {
		if err := os.Remove(f); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove %s: %w", f, err)
		}
	}

	return nil
}

// BackupState creates a backup of the current state in a target directory.
func (c *Copier) BackupState(targetDir string) (string, error) {
	statePath := filepath.Join(targetDir, "terraform.tfstate")
	backupPath := filepath.Join(targetDir, "terraform.tfstate.tfsync-backup")

	data, err := os.ReadFile(statePath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil // No state to backup
		}
		return "", fmt.Errorf("failed to read state: %w", err)
	}

	if err := os.WriteFile(backupPath, data, 0644); err != nil {
		return "", fmt.Errorf("failed to write backup: %w", err)
	}

	return backupPath, nil
}

// RestoreState restores state from a backup.
func (c *Copier) RestoreState(targetDir, backupPath string) error {
	if backupPath == "" {
		return nil // No backup to restore
	}

	data, err := os.ReadFile(backupPath)
	if err != nil {
		return fmt.Errorf("failed to read backup: %w", err)
	}

	statePath := filepath.Join(targetDir, "terraform.tfstate")
	if err := os.WriteFile(statePath, data, 0644); err != nil {
		return fmt.Errorf("failed to restore state: %w", err)
	}

	return nil
}
